from PyQt6 import QtCore, QtGui, QtWidgets
from addProductDialogUi import Ui_Dialog

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(1280, 800))
        Form.setMaximumSize(QtCore.QSize(1280, 800))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.menuBar1 = QtWidgets.QHBoxLayout()
        self.menuBar1.setObjectName("menuBar1")
        self.productsButton = QtWidgets.QPushButton(parent=Form)
        self.productsButton.setMinimumSize(QtCore.QSize(150, 35))
        self.productsButton.setMaximumSize(QtCore.QSize(400, 35))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.productsButton.setFont(font)
        self.productsButton.setObjectName("productsButton")
        self.menuBar1.addWidget(self.productsButton)
        self.categoriesButton = QtWidgets.QPushButton(parent=Form)
        self.categoriesButton.setMinimumSize(QtCore.QSize(150, 35))
        self.categoriesButton.setMaximumSize(QtCore.QSize(400, 35))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.categoriesButton.setFont(font)
        self.categoriesButton.setObjectName("categoriesButton")
        self.menuBar1.addWidget(self.categoriesButton)
        self.salesButton = QtWidgets.QPushButton(parent=Form)
        self.salesButton.setMinimumSize(QtCore.QSize(150, 35))
        self.salesButton.setMaximumSize(QtCore.QSize(400, 35))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.salesButton.setFont(font)
        self.salesButton.setObjectName("salesButton")
        self.menuBar1.addWidget(self.salesButton)
        spacerItem = QtWidgets.QSpacerItem(600, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.menuBar1.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.menuBar1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(6, -1, 6, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.allSmthLabel = QtWidgets.QLabel(parent=Form)
        self.allSmthLabel.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(22)
        font.setBold(True)
        self.allSmthLabel.setFont(font)
        self.allSmthLabel.setObjectName("allSmthLabel")
        self.verticalLayout.addWidget(self.allSmthLabel)
        self.searchLabel = QtWidgets.QLabel(parent=Form)
        self.searchLabel.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(18)
        self.searchLabel.setFont(font)
        self.searchLabel.setObjectName("searchLabel")
        self.verticalLayout.addWidget(self.searchLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchEdit = QtWidgets.QLineEdit(parent=Form)
        self.searchEdit.setMinimumSize(QtCore.QSize(0, 35))
        self.searchEdit.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        self.searchEdit.setFont(font)
        self.searchEdit.setObjectName("searchEdit")
        self.horizontalLayout.addWidget(self.searchEdit)
        self.searchButton = QtWidgets.QPushButton(parent=Form)
        self.searchButton.setMinimumSize(QtCore.QSize(0, 35))
        self.searchButton.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        self.searchButton.setFont(font)
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout.addWidget(self.searchButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 35, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.addButton = QtWidgets.QPushButton(parent=Form)
        self.addButton.setMinimumSize(QtCore.QSize(0, 35))
        self.addButton.setMaximumSize(QtCore.QSize(200, 35))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(26)
        self.addButton.setFont(font)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout.addWidget(self.addButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableView = QtWidgets.QTableView(parent=Form)
        self.tableView.setMinimumSize(QtCore.QSize(1250, 0))
        self.tableView.setMaximumSize(QtCore.QSize(1250, 600))
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        
        self.categoriesButton.clicked.connect(self.on_categoriesButton_clicked)
        self.productsButton.clicked.connect(self.on_productsButton_clicked)
        self.salesButton.clicked.connect(self.on_salesButton_clicked)
        self.addButton.clicked.connect(self.on_addButton_clicked)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.productsButton.setText(_translate("Form", "Изделия"))
        self.categoriesButton.setText(_translate("Form", "Категории изделий"))
        self.salesButton.setText(_translate("Form", "Акции на изделия"))
        self.allSmthLabel.setText(_translate("Form", "Все изделия"))
        self.searchLabel.setText(_translate("Form", "Поиск по артикулу или наименованию"))
        self.searchButton.setText(_translate("Form", "Поиск"))
        self.addButton.setText(_translate("Form", "+"))

    def on_categoriesButton_clicked(self):
        self.allSmthLabel.setText("Все категории")
        self.searchLabel.setText("Поиск по наименованию категории")

    def on_productsButton_clicked(self):
        self.allSmthLabel.setText("Все изделия")
        self.searchLabel.setText("Поиск по артикулу или наименованию")

    def on_salesButton_clicked(self):
        self.allSmthLabel.setText("Все акции")
        self.searchLabel.setText("Поиск по наименованию акции")

    def on_addButton_clicked(self):
        self.addDialog = QtWidgets.QDialog()
        self.ui_addDialog = Ui_Dialog()
        self.ui_addDialog.setupUi(self.addDialog)
        self.addDialog.show()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
