
from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 688)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(700, 688))
        Dialog.setMaximumSize(QtCore.QSize(700, 688))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(10, -1, 10, -1)
        self.gridLayout.setHorizontalSpacing(32)
        self.gridLayout.setVerticalSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.descriptionLabel = QtWidgets.QLabel(parent=Dialog)
        self.descriptionLabel.setMaximumSize(QtCore.QSize(350, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        self.descriptionLabel.setFont(font)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.gridLayout.addWidget(self.descriptionLabel, 5, 0, 1, 2)
        self.belkiLabel = QtWidgets.QLabel(parent=Dialog)
        self.belkiLabel.setMaximumSize(QtCore.QSize(350, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        self.belkiLabel.setFont(font)
        self.belkiLabel.setObjectName("belkiLabel")
        self.gridLayout.addWidget(self.belkiLabel, 7, 1, 1, 1)
        self.uglevodiLabel = QtWidgets.QLabel(parent=Dialog)
        self.uglevodiLabel.setMaximumSize(QtCore.QSize(350, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        self.uglevodiLabel.setFont(font)
        self.uglevodiLabel.setObjectName("uglevodiLabel")
        self.gridLayout.addWidget(self.uglevodiLabel, 9, 1, 1, 1)
        self.picInsertButton = QtWidgets.QPushButton(parent=Dialog)
        self.picInsertButton.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        self.picInsertButton.setFont(font)
        self.picInsertButton.setObjectName("picInsertButton")
        self.gridLayout.addWidget(self.picInsertButton, 11, 0, 1, 1)
        self.productSelfpriceLabel = QtWidgets.QLabel(parent=Dialog)
        self.productSelfpriceLabel.setMaximumSize(QtCore.QSize(350, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        self.productSelfpriceLabel.setFont(font)
        self.productSelfpriceLabel.setObjectName("productSelfpriceLabel")
        self.gridLayout.addWidget(self.productSelfpriceLabel, 3, 1, 1, 1)
        self.productSelfpriceEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.productSelfpriceEdit.setMaximumSize(QtCore.QSize(350, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.productSelfpriceEdit.setFont(font)
        self.productSelfpriceEdit.setObjectName("productSelfpriceEdit")
        self.gridLayout.addWidget(self.productSelfpriceEdit, 4, 1, 1, 1)
        self.uglevodiEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.uglevodiEdit.setMaximumSize(QtCore.QSize(350, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.uglevodiEdit.setFont(font)
        self.uglevodiEdit.setObjectName("uglevodiEdit")
        self.gridLayout.addWidget(self.uglevodiEdit, 10, 1, 1, 1)
        self.addSmthLabel = QtWidgets.QLabel(parent=Dialog)
        self.addSmthLabel.setMaximumSize(QtCore.QSize(350, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(24)
        font.setBold(True)
        self.addSmthLabel.setFont(font)
        self.addSmthLabel.setObjectName("addSmthLabel")
        self.gridLayout.addWidget(self.addSmthLabel, 0, 0, 1, 2)
        self.productNameEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.productNameEdit.setEnabled(True)
        self.productNameEdit.setMaximumSize(QtCore.QSize(350, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.productNameEdit.setFont(font)
        self.productNameEdit.setObjectName("productNameEdit")
        self.gridLayout.addWidget(self.productNameEdit, 2, 0, 1, 1)
        self.zhiriLabel = QtWidgets.QLabel(parent=Dialog)
        self.zhiriLabel.setMaximumSize(QtCore.QSize(350, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        self.zhiriLabel.setFont(font)
        self.zhiriLabel.setObjectName("zhiriLabel")
        self.gridLayout.addWidget(self.zhiriLabel, 9, 0, 1, 1)
        self.belkiEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.belkiEdit.setMaximumSize(QtCore.QSize(350, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.belkiEdit.setFont(font)
        self.belkiEdit.setObjectName("belkiEdit")
        self.gridLayout.addWidget(self.belkiEdit, 8, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_2.setMaximumSize(QtCore.QSize(350, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 12, 0, 1, 1)
        self.productPriceLabel = QtWidgets.QLabel(parent=Dialog)
        self.productPriceLabel.setMaximumSize(QtCore.QSize(350, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        self.productPriceLabel.setFont(font)
        self.productPriceLabel.setObjectName("productPriceLabel")
        self.gridLayout.addWidget(self.productPriceLabel, 3, 0, 1, 1)
        self.categoryLabel = QtWidgets.QLabel(parent=Dialog)
        self.categoryLabel.setMaximumSize(QtCore.QSize(350, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        self.categoryLabel.setFont(font)
        self.categoryLabel.setObjectName("categoryLabel")
        self.gridLayout.addWidget(self.categoryLabel, 1, 1, 1, 1)
        self.energyvalueEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.energyvalueEdit.setMaximumSize(QtCore.QSize(350, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.energyvalueEdit.setFont(font)
        self.energyvalueEdit.setObjectName("energyvalueEdit")
        self.gridLayout.addWidget(self.energyvalueEdit, 8, 0, 1, 1)
        self.energyvalueLabel = QtWidgets.QLabel(parent=Dialog)
        self.energyvalueLabel.setMaximumSize(QtCore.QSize(350, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        self.energyvalueLabel.setFont(font)
        self.energyvalueLabel.setObjectName("energyvalueLabel")
        self.gridLayout.addWidget(self.energyvalueLabel, 7, 0, 1, 1)
        self.productPriceEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.productPriceEdit.setMaximumSize(QtCore.QSize(350, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.productPriceEdit.setFont(font)
        self.productPriceEdit.setObjectName("productPriceEdit")
        self.gridLayout.addWidget(self.productPriceEdit, 4, 0, 1, 1)
        self.productNameLabel = QtWidgets.QLabel(parent=Dialog)
        self.productNameLabel.setMaximumSize(QtCore.QSize(350, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        font.setBold(False)
        self.productNameLabel.setFont(font)
        self.productNameLabel.setObjectName("productNameLabel")
        self.gridLayout.addWidget(self.productNameLabel, 1, 0, 1, 1)
        self.zhiriEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.zhiriEdit.setMaximumSize(QtCore.QSize(350, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.zhiriEdit.setFont(font)
        self.zhiriEdit.setObjectName("zhiriEdit")
        self.gridLayout.addWidget(self.zhiriEdit, 10, 0, 1, 1)
        self.categoriesComboBox = QtWidgets.QComboBox(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.categoriesComboBox.sizePolicy().hasHeightForWidth())
        self.categoriesComboBox.setSizePolicy(sizePolicy)
        self.categoriesComboBox.setMaximumSize(QtCore.QSize(350, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(14)
        self.categoriesComboBox.setFont(font)
        self.categoriesComboBox.setObjectName("categoriesComboBox")
        self.gridLayout.addWidget(self.categoriesComboBox, 2, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_3.setMaximumSize(QtCore.QSize(350, 30))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 12, 1, 1, 1)
        self.descriptionTextEdit = QtWidgets.QTextEdit(parent=Dialog)
        self.descriptionTextEdit.setMaximumSize(QtCore.QSize(700, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.descriptionTextEdit.setFont(font)
        self.descriptionTextEdit.setObjectName("descriptionTextEdit")
        self.gridLayout.addWidget(self.descriptionTextEdit, 6, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.descriptionLabel.setText(_translate("Dialog", "Описание изделия"))
        self.belkiLabel.setText(_translate("Dialog", "Белки г.:"))
        self.uglevodiLabel.setText(_translate("Dialog", "Углеводы г.:"))
        self.picInsertButton.setText(_translate("Dialog", "Загрузить фотографию изделия"))
        self.productSelfpriceLabel.setText(_translate("Dialog", "Себестоимость изделия руб.:"))
        self.addSmthLabel.setText(_translate("Dialog", "Добавить изделие"))
        self.zhiriLabel.setText(_translate("Dialog", "Жиры г.:"))
        self.pushButton_2.setText(_translate("Dialog", "Добавить"))
        self.productPriceLabel.setText(_translate("Dialog", "Цена изделия руб.:"))
        self.categoryLabel.setText(_translate("Dialog", "Категория:"))
        self.energyvalueLabel.setText(_translate("Dialog", "Энергетическая ценность кал.:"))
        self.productNameLabel.setText(_translate("Dialog", "Наименование изделия:"))
        self.pushButton_3.setText(_translate("Dialog", "Отмена"))
        self.descriptionTextEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">fffffff</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
